### ISSUE TITLE
Feature request - Board variant based on ESP32

### ISSUE THREAD

**Issue by pandel** [wladwnt/wled#3]
Hi!

First, your board (v6_mini) works perfectly well! Many thanks for that.

I stumbled upon the sound reactive fork of WLED (https://github.com/atuline/WLED) which can be used (somewhat limited, support deprecated) with ESP8266 and (full featured) ESP32. Nevertheless, I added a MAX4466 to my board and it works, really nice! But the limitations of the ESP8266 are clearly visible in this regard.

So, perhaps it would be nice, if you'd design your board around a ESP32 (Wemos ESP32 D1 mini, INMP441), additionally. This would make it possible to use the mentioned fork with all its features. And as the fork is also being discussed in the official WLED discord channel, I think, it could also be possible that the features will be integrated into the main repo someday...

Regards,
Holger

**Comment by wladwnt** [comment]
ESP32 in D1 mini format instead of ESP8266 D1 mini can be used with the board without any changes. Just right GPIO numbers must be selected in WLED configuration (GPIO 16 for Data and, if required, GPIO17 for Clock).

**Comment by pandel** [comment]
Many thanks! I think, I'll give it a try...

**Comment by pandel** [comment]
Just for the record: it worked out perfectly with the ESP32. Soundreactive WLED is really cool :-)
